#!/usr/bin/env python3
"""Tidy exam paper PDFs into clean per-question JSON using a vision LLM.

Each paper PDF is rendered page by page and sent to a vision model together
with the answer-key PDF images. The model extracts every COMPLETE question
visible on the page. Because some questions span two pages, the previous
page's last question is carried forward: the model may return an
``updated_previous`` that merges content across the boundary, plus any
``questions`` that are newly complete on the current page.

The LLM's role is TIDYING, not grading: it faithfully transcribes the paper's
and the official answer key's content — including any mistakes in the key.
Accuracy is checked separately by scripts/validate_tidy_questions.py.

Output schema per question (all text fields are Markdown):
    {
      "background":   string,  # Markdown, equations as LaTeX
      "question":     string,  # Markdown
      "options":      [{"code": "A", "label": "..."}],
      "answer":       string,
      "explanations": string,  # Markdown
      "section":      "reading_writing" | "math",
      "module":       1 | 2,
      "number":       int,
      "page":         int      # source page_idx
    }

Usage:
    python scripts/tidy_questions.py \\
        --model gpt-5.6-terra \\
        --pair papers/pdfs/2024/demo-paper.pdf \\
               papers/pdfs/2024/demo-key.pdf
"""

from __future__ import annotations

import argparse
import base64
import io
import json
import os
import re
import sys
import time
from pathlib import Path

import paper_images

PROJECT_ROOT = Path(__file__).resolve().parent.parent
IMAGE_ROOTS = [PROJECT_ROOT / "papers" / "jsons", PROJECT_ROOT / "papers" / "mds"]

DEFAULT_MODEL = "gpt-5.6-terra"
DEFAULT_FLASH_MODEL = "gpt-5.6-luna"

SYSTEM_PROMPT = r"""\
You are an expert exam question tidy-up assistant. You are given the image of ONE page of an exam paper and images of the paper's official answer key.

Your job is TIDYING, not grading: extract, structure, and transcribe it verbatim. Treat the official answer key as ground truth for transcription — never correct, rewrite, second-guess, or argue with its answers or explanations, even when they look wrong. Never change a letter or value because you believe the key is mistaken. Accuracy checking happens later. If the official answer key includes an explanation for a question, transcribe it verbatim — do not rewrite. If the key has no explanation or it is empty, write a concise 1-3 sentence explanation yourself, prefixed with "Note: This explanation was generated by the model as no official explanation was provided. ".

You may also be given a PREVIOUS QUESTION for reference only. It is the last question from the previous page and is provided SOLELY to handle a split question. It may be completely UNRELATED to the current page. ONLY set "updated_previous" if the current page is clearly a direct continuation of that exact question (same passage / same number split across pages). Otherwise set "updated_previous" to null. If the current page shows NEW question(s), transcribe them normally in "questions" — do NOT copy the previous question into "questions" and do NOT try to merge unrelated content.

Output ONLY a JSON object with exactly two keys:
- "updated_previous": null, or the merged complete version of the previous question if it was genuinely split (must keep same "section"/"module"/"number" as the reference).
- "questions": array (possibly empty) of question objects that are COMPLETELY visible and self-contained on THIS page. Never include the previous question here. Each object MUST have EXACTLY these keys with correct types — no extra keys, no missing keys:
  - "background": string, all stem content EXCEPT the final interrogative sentence that instructs the student to input an answer (that final sentence ending with "?" is the question). Verbatim Markdown, "" if none. Use Markdown for paragraphs and LaTeX for math ($...$ inline, $$...$$ display).
  - "question": string, NON-EMPTY, ONLY the final interrogative sentence that directly asks for the answer (ends with "?"), verbatim Markdown with LaTeX. THIS FIELD IS REQUIRED — never leave it empty. If you cannot identify a complete question, return empty array instead. Example: background="$g(x)=x^2+\\frac{27}{2}x$" question="Which expression represents the minimum value of the given function?"
  - "options": array of {"code": "A", "label": "<text>"} (A-D, sometimes A-E); [] for free-response math.
  - "answer": string, option code or value transcribed verbatim from the official answer key. MUST equal one of "options" codes when options exist. For "x" in the key, choose the most likely correct option yourself.
  - "explanations": string, transcribe the key's explanation verbatim if present (as Markdown); otherwise write a concise 1-3 sentence explanation yourself prefixed with "Note: This explanation was generated by the model as no official explanation was provided. " — if honest explanation is impossible, write "No official explanation provided in the answer key."
  - "section": string, exactly "reading_writing" or "math"
  - "module": integer, exactly 1 or 2
  - "number": integer, question number within its module (Reading & Writing 1-27, Math 1-22 per module)

Example of valid output:
{"updated_previous": null, "questions": [{"background": "", "question": "What is $2+2$?", "options": [{"code": "A", "label": "4"}], "answer": "A", "explanations": "No official explanation provided in the answer key.", "section": "math", "module": 1, "number": 1}]}

Rules:
1. Output ONLY the JSON object described above. No markdown fences, no prose.
2. Keep all wording verbatim in Markdown. Preserve paragraphs, lists, and emphasis. Write ALL mathematical expressions in LaTeX: inline math with $...$, display math with $$...$$ on its own line. Use \\frac, \\sqrt, \\sum, ^, _, etc. (in JSON backslashes must be escaped as \\ so the stored string contains \frac). Example: "$g(x)=x^2+\\frac{27}{2}x$" for the stem. Be careful with $: it starts/ends math. For literal dollar amounts (e.g., $15) write \$15 in Markdown (which in JSON must be written as \\$15 — a single backslash + $). Do NOT write \\$$ or $$ for currency. Always escape backslashes as \\ in JSON (so \\left, \\right, \\frac in the stored string are written as \\\\left etc. in JSON — a single \f would be invalid). For line breaks in Markdown, use single \n (\n in JSON) for a new line, not \\n.
3. The paper has Section 1 = Reading and Writing (英语) and Section 2 = Math (数学), each split into Module 1/2 (M1/M2). Boundaries appear in page headers like "Section 1, Module 1: Reading and Writing" or "Section 2, Module 2: Math".
4. Answer key format: "1-5: AxBAA" means Q1=A, Q2=x, etc. Math may be "3.43" or "7.B". Transcribe verbatim; never change because you believe the key is mistaken.
5. Ignore UI chrome: timers, "Mark for Review", "Hide", "Highlights & Notes More", "Directions".
6. Do not translate text.
7. Figures: when a question refers to a diagram/table/figure, insert [image: <id>] at the appropriate place in background/question/options/explanations using ONLY the cropped figure ids provided for this page (e.g. [image: abc123]). Attached cropped figures correspond one-to-one, in order, to the [image: <id>] placeholders that will be listed. Do NOT invent ids like [image: graph] or [image: figure1] — if no figure id is listed for this page, do not insert any image placeholder.
"""

def pdf_to_images(pdf: Path, dpi: int = 150) -> list[bytes]:
    try:
        import fitz
        doc = fitz.open(str(pdf))
        out: list[bytes] = []
        for page in doc:
            pix = page.get_pixmap(dpi=dpi)
            out.append(pix.tobytes("png"))
        return out
    except ImportError:
        pass
    except Exception as exc:
        raise RuntimeError(f"failed to render {pdf}: {exc}") from exc
    import subprocess
    import tempfile
    with tempfile.TemporaryDirectory() as tmp:
        prefix = Path(tmp) / "pg"
        cmd = ["pdftoppm", "-r", str(dpi), "-png", str(pdf), str(prefix)]
        result = subprocess.run(cmd, capture_output=True)
        if result.returncode != 0:
            raise RuntimeError(f"pdftoppm failed for {pdf}: {result.stderr.decode()}")
        files = sorted(Path(tmp).glob("pg-*.png"))
        if not files:
            files = sorted(Path(tmp).glob("pg*.png"))
        return [f.read_bytes() for f in files]

def image_bytes_to_data_url(image_bytes: bytes, mime: str = "image/png") -> str:
    b64 = base64.b64encode(image_bytes).decode("ascii")
    return f"data:{mime};base64,{b64}"

def _scan_json(raw: str) -> str | None:
    for start in range(len(raw)):
        if raw[start] not in "[{":
            continue
        depth = 0
        in_str = False
        esc = False
        for i in range(start, len(raw)):
            c = raw[i]
            if in_str:
                if esc:
                    esc = False
                elif c == "\\":
                    esc = True
                elif c == '"':
                    in_str = False
                continue
            if c == '"':
                in_str = True
            elif c in "[{":
                depth += 1
            elif c in "]}":
                depth -= 1
                if depth == 0:
                    return raw[start : i + 1]
    return None

def _fix_json_escapes(raw: str) -> str:
    # Fix invalid single-backslash LaTeX escapes for JSON: \frac, \left, \$, etc.
    # JSON only allows \" \\ \/ \b \f \n \r \t \u; LaTeX uses \f, \r etc. which are valid JSON but wrong.
    # So double-escape any single backslash before letters/digits/$()[]{} to preserve LaTeX.
    return re.sub(r'(?<!\\)\\(?=[A-Za-z0-9\$\(\)\{\}\[\]])', r'\\\\', raw)

def parse_json_response(raw: str):
    if not raw:
        return None
    raw = raw.strip()
    fenced = re.search(r"```(?:json)?\s*(.*?)```", raw, re.DOTALL | re.IGNORECASE)
    if fenced:
        raw = fenced.group(1).strip()
    # pre-fix common LaTeX single-backslash issues before JSON parse
    raw_fixed = _fix_json_escapes(raw)
    try:
        return json.loads(raw_fixed)
    except json.JSONDecodeError:
        pass
    candidate = _scan_json(raw_fixed)
    if candidate:
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
    # fallback try without fix
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        pass
    candidate2 = _scan_json(raw)
    if candidate2:
        try:
            return json.loads(candidate2)
        except json.JSONDecodeError:
            pass
    return None

SECTION_VALUES = ("reading_writing", "math")

def normalize_code(code: str) -> str:
    m = re.match(r"[（(]?\s*([A-Ea-e])\s*[)）]?\.?$", code.strip())
    return m.group(1).upper() if m else code.strip()

def normalize_section(value) -> str:
    s = str(value or "").strip().lower().replace(" ", "_").replace("-", "_")
    if s in SECTION_VALUES:
        return s
    return {
        "rw": "reading_writing",
        "english": "reading_writing",
        "英语": "reading_writing",
        "reading": "reading_writing",
        "writing": "reading_writing",
        "阅读": "reading_writing",
        "阅读与写作": "reading_writing",
        "阅读和写作": "reading_writing",
        "mathematics": "math",
        "数学": "math",
    }.get(s, "")

def normalize_module(value) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, (int, float)):
        return int(value) if int(value) in (1, 2) else 0
    m = re.fullmatch(r"\s*[Mm]?([12])\s*", str(value or ""))
    return int(m.group(1)) if m else 0

def normalize_number(value) -> int:
    if isinstance(value, bool):
        return 0
    if isinstance(value, (int, float)):
        return int(value) if value > 0 else 0
    m = re.fullmatch(r"\s*#?\s*(\d{1,3})\s*", str(value or ""))
    return int(m.group(1)) if m else 0

def normalize_questions(items) -> tuple[list[dict], list[str]]:
    questions: list[dict] = []
    issues: list[str] = []
    for i, item in enumerate(items):
        if not isinstance(item, dict):
            issues.append(f"item {i}: not an object")
            continue
        question = str(item.get("question") or "").strip()
        if not question:
            issues.append(f"item {i}: missing question text")
            continue
        options: list[dict] = []
        for opt in item.get("options") or []:
            if not isinstance(opt, dict):
                continue
            code = normalize_code(str(opt.get("code") or ""))
            label = str(opt.get("label") or "").strip()
            if code and label:
                options.append({"code": code, "label": label})
        answer = str(item.get("answer") or "").strip()
        codes = [o["code"] for o in options]
        if codes and answer not in codes:
            matched = next(
                (o["code"] for o in options if o["label"].lower() == answer.lower()),
                None,
            )
            if matched:
                answer = matched
            else:
                issues.append(
                    f"item {i} ('{question[:60]}...'): answer {answer!r} "
                    f"not in option codes {codes}"
                )
        page_val = item.get("page")
        try:
            page_norm = int(page_val) if page_val is not None and str(page_val).strip() != "" else None
        except Exception:
            page_norm = None
        questions.append(
            {
                "background": str(item.get("background") or ""),
                "question": question,
                "options": options,
                "answer": answer,
                "explanations": str(item.get("explanations") or ""),
                "section": normalize_section(item.get("section")),
                "module": normalize_module(item.get("module")),
                "number": normalize_number(item.get("number")),
                "page": page_norm,
            }
        )
    return questions, issues

def dedupe(questions: list[dict]) -> tuple[list[dict], int]:
    seen: set[tuple] = set()
    out: list[dict] = []
    skipped = 0
    for q in questions:
        q_norm = re.sub(r"\s+", " ", q["question"]).strip().lower()
        bg_norm = re.sub(r"\s+", " ", q.get("background") or "").strip().lower()[:300]
        opts_norm = tuple(
            (o.get("code", ""), re.sub(r"\s+", " ", o.get("label") or "").strip().lower())
            for o in (q.get("options") or [])
        )
        # include section/module to avoid cross-module collisions, but not number (unreliable)
        key = (q_norm, bg_norm, opts_norm, q.get("section"), q.get("module"))
        if key in seen:
            skipped += 1
            continue
        seen.add(key)
        out.append(q)
    return out, skipped

def _fix_parsed_text(s: str) -> str:
    # Fix \n not followed by lowercase -> newline, and fix weird \$$ currency double-escape
    s = re.sub(r'\\n(?![a-z])', '\n', s)
    # Fix LLM's weird \$$15 (\ + $$) for currency -> should be \$15 (\ + $)
    s = s.replace('\\$$', '\\$')
    # Also fix any remaining \$ that should be single (already correct) - ensure not double
    return s

def _fix_question_texts(q: dict) -> dict:
    for field in ("background", "question", "explanations"):
        if isinstance(q.get(field), str):
            q[field] = _fix_parsed_text(q[field])
    if isinstance(q.get("options"), list):
        for opt in q["options"]:
            if isinstance(opt, dict) and isinstance(opt.get("label"), str):
                opt["label"] = _fix_parsed_text(opt["label"])
    return q

def _parse_page_response(raw: str):
    data = parse_json_response(raw)
    if data is None:
        return None
    if isinstance(data, list):
        return {"updated_previous": None, "questions": data}
    if isinstance(data, dict):
        if "questions" in data or "updated_previous" in data:
            upd = data.get("updated_previous")
            qs = data.get("questions")
            if qs is None and isinstance(data.get("updated"), list):
                qs = data.get("updated")
            if not isinstance(qs, list):
                qs = []
            return {"updated_previous": upd, "questions": qs}
        if isinstance(data.get("questions"), list):
            return {"updated_previous": None, "questions": data["questions"]}
    return None

def extract_page(
    model: str,
    content,
    *,
    json_mode: bool,
    max_retries: int,
    timeout: int,
) -> dict:
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": content},
    ]
    last_error: Exception | None = None
    for attempt in range(max_retries + 1):
        from litellm import completion

        kwargs: dict = {"model": model, "messages": messages, "timeout": timeout}
        if json_mode:
            kwargs["response_format"] = {"type": "json_object"}
        try:
            resp = completion(**kwargs)
            raw = resp.choices[0].message.content or ""
        except Exception as exc:
            last_error = exc
            time.sleep(1 + attempt)
            continue
        parsed = _parse_page_response(raw)
        if parsed is not None:
            return parsed
        last_error = ValueError(f"response was not usable JSON: {raw[:200]!r}")
        messages.append({"role": "assistant", "content": raw})
        messages.append(
            {
                "role": "user",
                "content": (
                    "That was not valid JSON. Output ONLY a JSON object with "
                    '"updated_previous" and "questions" as described and nothing else.'
                ),
            }
        )
    raise RuntimeError(
        f"failed after {max_retries + 1} attempt(s): {last_error}"
    ) from last_error

def parse_index_range(raw: str, total: int, what: str) -> tuple[int, int] | None:
    m = re.fullmatch(r"\s*(\d+)\s*-\s*(\d+)\s*", raw or "")
    if not m:
        raise argparse.ArgumentTypeError(
            f"expected 'START-END' {what} indices, got {raw!r}"
        )
    start, end = int(m.group(1)), int(m.group(2))
    if start > end:
        raise argparse.ArgumentTypeError(f"range start {start} > end {end}")
    if end >= total:
        raise argparse.ArgumentTypeError(
            f"range {start}-{end} exceeds {what} count {total}"
        )
    return start, end


def _paper_json_path(paper: Path) -> Path | None:
    for base in [PROJECT_ROOT / "papers" / "jsons", PROJECT_ROOT / "papers" / "mds"]:
        for year_dir in base.glob("*"):
            cand = year_dir / f"{paper.stem}.json"
            if cand.is_file():
                return cand
        cand = base / f"{paper.stem}.json"
        if cand.is_file():
            return cand
    # fallback: alongside pdfs year
    try:
        rel_year = paper.parent.name
        cand = PROJECT_ROOT / "papers" / "jsons" / rel_year / f"{paper.stem}.json"
        if cand.is_file():
            return cand
    except Exception:
        pass
    return None

def _load_page_image_refs(paper: Path) -> dict[int, list[str]]:
    j = _paper_json_path(paper)
    if j is None:
        return {}
    try:
        data = json.loads(j.read_text(encoding="utf-8"))
    except Exception:
        return {}
    out: dict[int, list[str]] = {}
    for el in data:
        if isinstance(el, dict) and el.get("img_path"):
            try:
                pi = int(el.get("page_idx", -1))
            except Exception:
                continue
            out.setdefault(pi, []).append(el["img_path"])
    return out

def process_pair(
    args,
    paper: Path,
    answer: Path,
    index: int,
    total_pairs: int,
) -> tuple[int, int, int]:
    page_images = pdf_to_images(paper, dpi=args.dpi)
    answer_images = pdf_to_images(answer, dpi=args.dpi)
    total_pages = len(page_images)
    print(f"  rendered {total_pages} paper page(s), {len(answer_images)} answer page(s)")

    if args.pages:
        start, end = parse_index_range(args.pages, total_pages, "page")
        page_indices = [i for i in range(total_pages) if start <= i <= end]
    else:
        page_indices = list(range(total_pages))

    if not page_indices:
        print(f"  ! no page matches requested range in {paper.name}", file=sys.stderr)
        return 0, 0, 0

    answer_urls = [image_bytes_to_data_url(b) for b in answer_images]

    page_image_refs = _load_page_image_refs(paper)
    img_index = paper_images.ImageIndex(IMAGE_ROOTS) if page_image_refs else None

    all_questions: list[dict] = []
    all_issues: list[str] = []
    failures = 0
    prev: dict | None = None

    for n, page_idx in enumerate(page_indices, 1):
        page_bytes = page_images[page_idx]
        page_url = image_bytes_to_data_url(page_bytes)

        fig_refs: list[str] = page_image_refs.get(page_idx, [])
        min_size = getattr(args, 'min_image_size', paper_images.DEFAULT_MIN_IMAGE_SIZE)
        fig_refs = [r for r in fig_refs if paper_images.is_figure(img_index.size(Path(r).name) if img_index else None, min_size)] if img_index else []
        fig_map = paper_images.build_figure_map(fig_refs) if fig_refs else {}
        short_to_long = {v: k for k, v in fig_map.items()}
        fig_ids = list(fig_map.values())
        figure_urls: list[str] = []
        if fig_refs and img_index:
            paths = [img_index.path(Path(r).name) for r in fig_refs]
            # encode cropped figures as data urls for attachment
            for pp in paths:
                if pp and pp.is_file():
                    try:
                        figure_urls.append(image_bytes_to_data_url(pp.read_bytes(), mime="image/jpeg" if pp.suffix.lower() in (".jpg",".jpeg") else "image/png"))
                    except Exception:
                        pass

        text = f"PAPER: {paper.stem}\nPAGE: {page_idx} ({n}/{len(page_indices)})"
        if fig_ids:
            text += "\nCropped figures for this page: " + ", ".join(f"[image: {sid}]" for sid in fig_ids) + " (each corresponds to an attached cropped figure image, in order)"
        if prev is not None:
            text += (
                "\n\nPREVIOUS QUESTION FOR REFERENCE ONLY (from previous page, may be UNRELATED to current page):\n"
                f"{json.dumps(prev, ensure_ascii=False, indent=2)}\n"
                "ONLY set 'updated_previous' if the current page is a direct continuation of THIS exact question (visibly split). Otherwise set 'updated_previous' to null. If the image shows NEW question(s), transcribe them in 'questions' — do NOT copy or merge the reference."
            )
        text += "\n\nAttached: image of the current paper page, followed by the answer-key images."
        if fig_ids:
            text += " Cropped figure images for this page are attached after the page image; reference them with their [image: id] in your JSON."

        content: list[dict] = [
            {"type": "text", "text": text},
            {"type": "image_url", "image_url": {"url": page_url}},
        ]
        for url in figure_urls:
            content.append({"type": "image_url", "image_url": {"url": url}})
        for url in answer_urls:
            content.append({"type": "image_url", "image_url": {"url": url}})

        print(f"  [{index}/{total_pairs}] {paper.stem}: page {page_idx} ({n}/{len(page_indices)}) ...", end="", flush=True)
        try:
            parsed = extract_page(
                args.model,
                content,
                json_mode=args.json_mode,
                max_retries=args.max_retries,
                timeout=args.timeout,
            )
        except Exception as exc:
            failures += 1
            all_issues.append(f"page {page_idx}: {exc}")
            print(f" FAIL ({exc})", file=sys.stderr)
            continue

        upd = parsed.get("updated_previous")
        new_qs = parsed.get("questions") or []

        # rewrite short figure ids back to long refs in LLM output; also sanitize hallucinated ids like [image: graph]
        def rewrite_short(q: dict) -> dict:
            if short_to_long:
                for field in ("background", "question", "explanations"):
                    if isinstance(q.get(field), str):
                        q[field] = paper_images.rewrite_short_to_long(q[field], short_to_long)
                if isinstance(q.get("options"), list):
                    for opt in q["options"]:
                        if isinstance(opt, dict) and isinstance(opt.get("label"), str):
                            opt["label"] = paper_images.rewrite_short_to_long(opt["label"], short_to_long)
            # sanitize any remaining [image: ...] where ref is not a known hash (e.g. "graph")
            # if we have a figure for this page, replace generic refs with the first figure's long ref; otherwise drop
            generic_pat = re.compile(r"\[image:\s*([^\]]+?)\]")
            for field in ("background", "question", "explanations"):
                if isinstance(q.get(field), str) and "[image:" in q[field]:
                    def _sanitize(m):
                        ref = m.group(1).strip()
                        # already a known hash path or short id that was rewritten? keep as is
                        if ref in short_to_long or ref.startswith("images/") or len(ref) >= 12 and all(c in "0123456789abcdef" for c in ref.lower()):
                            return m.group(0)
                        # generic like "graph" -> replace with first figure if available else drop
                        if fig_refs:
                            return f"[image: {fig_refs[0]}]"
                        return ""
                    q[field] = generic_pat.sub(_sanitize, q[field])
            if isinstance(q.get("options"), list):
                for opt in q["options"]:
                    if isinstance(opt, dict) and isinstance(opt.get("label"), str) and "[image:" in opt["label"]:
                        def _sanitize2(m):
                            ref = m.group(1).strip()
                            if ref in short_to_long or ref.startswith("images/") or len(ref) >= 12 and all(c in "0123456789abcdef" for c in ref.lower()):
                                return m.group(0)
                            if fig_refs:
                                return f"[image: {fig_refs[0]}]"
                            return ""
                        opt["label"] = generic_pat.sub(_sanitize2, opt["label"])
            return q

        if upd is not None:
            if not isinstance(upd, dict):
                all_issues.append(f"page {page_idx}: updated_previous not an object")
            else:
                upd = rewrite_short(upd)
                upd = _fix_question_texts(upd)
                normed, issues = normalize_questions([upd])
                for q in normed:
                    if q.get("page") is None:
                        q["page"] = page_idx + 1
                all_issues.extend(f"page {page_idx} updated: {i}" for i in issues)
                if normed:
                    if all_questions:
                        # preserve original page if already set, otherwise use current
                        if normed[0].get("page") is None and all_questions[-1].get("page") is not None:
                            normed[0]["page"] = all_questions[-1]["page"]
                        all_questions[-1] = normed[0]
                        prev = normed[0]
                    else:
                        all_questions.append(normed[0])
                        prev = normed[0]
                else:
                    all_issues.append(f"page {page_idx}: updated_previous invalid")

        # rewrite figures in new questions
        new_qs = [rewrite_short(q) if isinstance(q, dict) else q for q in new_qs]
        new_qs = [_fix_question_texts(q) if isinstance(q, dict) else q for q in new_qs]
        normed_new, issues = normalize_questions(new_qs)
        for q in normed_new:
            if q.get("page") is None:
                q["page"] = page_idx + 1
        all_issues.extend(f"page {page_idx}: {i}" for i in issues)
        all_questions.extend(normed_new)
        if normed_new:
            prev = normed_new[-1]
        elif upd is None and all_questions:
            prev = all_questions[-1]
        else:
            pass

        print(f" {len(normed_new)} new" + (", 1 updated" if upd else "") + (f", {len(fig_refs)} figs" if fig_refs else ""))

    questions, skipped = dedupe(all_questions)
    out_dir = args.output_dir or (paper.parent.parent / "jsons" / paper.parent.name / "tidy")
    if str(out_dir) == ".":
        out_dir = Path("papers/jsons/tidy")
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = paper.stem
    out_path = out_dir / f"{stem}.json"
    out_path.write_text(json.dumps(questions, ensure_ascii=False, indent=2), encoding="utf-8")
    try:
        out_rel = out_path.relative_to(Path.cwd())
    except ValueError:
        out_rel = out_path
    print(f"  -> {out_rel}: {len(questions)} questions ({skipped} duplicate(s) dropped)")
    for issue in all_issues:
        print(f"  ! {issue}", file=sys.stderr)
    return len(page_indices), len(questions), failures


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Tidy exam paper PDFs into clean per-question JSON, one page at a time "
            "with vision LLM and cross-page handling."
        )
    )
    parser.add_argument(
        "--pair",
        nargs=2,
        action="append",
        required=True,
        metavar=("PAPER_PDF", "ANSWER_PDF"),
        help="Question paper PDF followed by its answer key PDF. Repeat for multiple papers.",
    )
    parser.add_argument(
        "--model",
        default=os.environ.get("LITELLM_MODEL", DEFAULT_FLASH_MODEL),
        help=f"litellm model string (default: $LITELLM_MODEL or {DEFAULT_FLASH_MODEL}).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        help="Directory for tidy JSON outputs (default: papers/jsons/<year>/tidy).",
    )
    parser.add_argument(
        "--pages",
        help="Process only pages with page_idx in START-END (0-based, e.g. 27-40).",
    )
    parser.add_argument(
        "--dpi",
        type=int,
        default=150,
        help="PDF render DPI (default: 150).",
    )
    parser.add_argument(
        "--min-image-size",
        type=int,
        default=paper_images.DEFAULT_MIN_IMAGE_SIZE,
        help=f"Keep a cropped image as a figure when its longer side >= N and shorter side >= 64 (default: N={paper_images.DEFAULT_MIN_IMAGE_SIZE}, i.e. 128*64).",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=2,
        help="LLM retries per page when JSON parsing fails (default: 2).",
    )
    parser.add_argument(
        "--timeout",
        type=int,
        default=300,
        help="Per-call timeout in seconds (default: 300).",
    )
    parser.add_argument(
        "--json-mode",
        action="store_true",
        help="Request provider-native JSON response format.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=1,
        help="Compatibility shim; sequential processing is required for cross-page handling, so batch is ignored.",
    )
    args = parser.parse_args()

    if args.dpi < 72 or args.dpi > 400:
        parser.error("--dpi must be between 72 and 400")

    try:
        import litellm
    except ImportError:
        print("litellm is not installed; run `uv sync` first.", file=sys.stderr)
        return 1
    litellm.suppress_debug_info = True

    if args.batch_size > 1:
        print("[--batch-size is ignored: pages are processed sequentially to handle cross-page questions]", file=sys.stderr)

    pairs = [(Path(q), Path(a)) for q, a in args.pair]
    for paper, answer in pairs:
        for path in (paper, answer):
            if not path.is_file():
                print(f"File not found: {path}", file=sys.stderr)
                return 1
            if path.suffix.lower() != ".pdf":
                print(f"Expected PDF file, got: {path}", file=sys.stderr)
                return 1

    total_failures = 0
    for index, (paper, answer) in enumerate(pairs, 1):
        print(f"\n=== [{index}/{len(pairs)}] {paper.name} + {answer.name}")
        try:
            pages, _questions, failures = process_pair(args, paper, answer, index, len(pairs))
            total_failures += failures
            if pages == 0:
                print("  (nothing to process)", file=sys.stderr)
        except Exception as exc:
            total_failures += 1
            print(f"  FAIL {paper.name}: {exc}", file=sys.stderr)

    if total_failures:
        print(f"\nFinished with {total_failures} page/paper failure(s).", file=sys.stderr)
        return 1
    print("\nDone.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
